### ISSUE TITLE
Example find_node.rs panics for some reasons

### ISSUE THREAD

**Issue by drHuangMHT** [raptorswing/rustydht-lib#65]
I'm randomly poking around the example [find_nodes.rs](https://github.com/raptorswing/rustydht-lib/blob/main/examples/find_nodes.rs). It will produce a proper output of nodes found before throwing out some panic information.
the backtrace displayed is here in [Ubuntu Pastebin](https://paste.ubuntu.com/p/YKySjqpb5f/)(expires in a week). The program will panic arbitrary times(which means it probably won't panic) with pretty much the same backtrace.  
Totally don't know what happened since I'm still a freshman.

**Comment by raptorswing** [comment]
Hi, 

Thanks for the report. Are you running find_nodes directly with `cargo run --example find_nodes` or something else?

Based on the trace, a mutex is returning the `WouldBlock` Err, which means that something else has the Mutex. find_nodes and the other examples (and tests) all run in tokio's `current_thread` mode, which only uses a single thread. So it's not expected to see a WouldBlock from the mutex.

I need to revise the mutex (use `lock()` instead of `try_lock()`) before the code will be ready for multi-threading.

Copying the backtrace from Ubuntu pastebin in case it is needed after it expires:
```
thread 'tokio-runtime-worker' panicked at 'thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: "WouldBlock"', called `Result::unwrap()` on an `Err` value: "WouldBlock"/home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/rustydht-lib-3.0.0/src/dht/dht.rs', :/home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/rustydht-lib-3.0.0/src/dht/dht.rs780::78050:
50stack backtrace:

   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1298:23
   4: rustydht_lib::dht::dht::DHT::ping_internal::{{closure}}::{{closure}}
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/rustydht-lib-3.0.0/src/dht/dht.rs:780:33
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
   6: rustydht_lib::shutdown::ShutdownReceiver::spawn_with_shutdown::{{closure}}::{{closure}}
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/macros/select.rs:505:49
   7: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/future/poll_fn.rs:38:9
   8: rustydht_lib::shutdown::ShutdownReceiver::spawn_with_shutdown::{{closure}}
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/rustydht-lib-3.0.0/src/shutdown.rs:38:13
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
  11: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/core.rs:161:17
  12: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/loom/std/unsafe_cell.rs:14:9
  13: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/core.rs:151:13
  14: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:461:19
  15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panic/unwind_safe.rs:271:9
  16: std::panicking::try::do_call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  17: __rust_try
  18: std::panicking::try
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  19: std::panic::catch_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  20: tokio::runtime::task::harness::poll_future
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:449:18
  21: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:98:27
  22: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:53:15
  23: tokio::runtime::task::raw::poll
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/raw.rs:113:5
  24: tokio::runtime::task::raw::RawTask::poll
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/raw.rs:70:18
  25: tokio::runtime::task::LocalNotified<S>::run
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/mod.rs:343:9
  26: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:420:13
  27: tokio::coop::with_budget::{{closure}}
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:102:9
  28: std::thread::local::LocalKey<T>::try_with
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
  29: std::thread::local::LocalKey<T>::with
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  30: tokio::coop::with_budget
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:95:5
  31: tokio::coop::budget
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:72:5
  32: tokio::runtime::thread_pool::worker::Context::run_task
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:419:9
  33: tokio::runtime::thread_pool::worker::Context::run
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:386:24
  34: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:371:17
  35: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/macros/scoped_tls.rs:61:9
  36: tokio::runtime::thread_pool::worker::run
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:368:5
  37: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:347:45
  38: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/blocking/task.rs:42:21
  39: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/core.rs:161:17
  40: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/loom/std/unsafe_cell.rs:14:9
  41: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/core.rs:151:13
  42: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:461:19
  43: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panic/unwind_safe.rs:271:9
  44: std::panicking::try::do_call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  45: __rust_try
  46: std::panicking::try
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  47: std::panic::catch_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  48: tokio::runtime::task::harness::poll_future
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:449:18
  49: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:98:27
  50: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:53:15
  51: tokio::runtime::task::raw::poll
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/raw.rs:113:5
  52: tokio::runtime::task::raw::RawTask::poll
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/raw.rs:70:18
  53: tokio::runtime::task::UnownedTask<S>::run
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/mod.rs:379:9
  54: tokio::runtime::blocking::pool::Inner::run
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/blocking/pool.rs:264:17
  55: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/drhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/blocking/pool.rs:244:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by raptorswing** [comment]
Give the multithread branch a try: https://github.com/raptorswing/rustydht-lib/tree/multithread

**Comment by drHuangMHT** [comment]
I copied the code into a main function of my own to test it's functionality. It's a pretty simple one just like this
```rust
#[tokio::main]
async fn main(){ /*code in the example, nothing else*/ }
```
So that's probably caused by multi-threading. I simply just don't want to clone the repo XD

**Comment by raptorswing** [comment]
Ok - that makes sense and I'm able to reproduce the issue. 

If you don't want to clone the multithread branch to try that out, you can instead just change your tokio macro to `#[tokio::main(flavor = "current_thread")]` and it should work fine.

**Comment by drHuangMHT** [comment]
Uh, one more thing. Isn't it that there is only one task running? Who else want to get the lock? Or why it want to get the lock it already has?
Not quite understand the behavior here.

**Comment by raptorswing** [comment]
The code does use multiple tokio tasks. And tokio tasks must implement `Send`. So basically, even if using tokio's `current_thread` runtime, tasks have to be written such that they can run multithreaded. I didn't see an easy way to make it work without a mutex. I'd be happy to be proven wrong! Probably there's a way to do it with message passing. I'm still fairly new to Rust and tokio.

In any case the 3.0.1 version changes the locking code to behave with either tokio runtime.
